table ClubAnalysis
	lineageTag: c256e28d-b454-45b4-a9bf-5574f00879b0

	column chance_of_playing_next_round
		dataType: string
		lineageTag: bb12536e-9d2d-4812-9cf0-b9268e59d976
		summarizeBy: none
		sourceColumn: chance_of_playing_next_round

		annotation SummarizationSetBy = Automatic

	column chance_of_playing_this_round
		dataType: string
		lineageTag: 35bd6fa2-f76d-4034-a607-23212f5ec9e4
		summarizeBy: none
		sourceColumn: chance_of_playing_this_round

		annotation SummarizationSetBy = Automatic

	column code
		dataType: string
		lineageTag: eaf66989-3a43-4798-bd38-3f4f1e5b4eac
		summarizeBy: none
		sourceColumn: code

		annotation SummarizationSetBy = Automatic

	column cost_change_event
		dataType: string
		lineageTag: bee3ce53-7a2a-46af-920d-10c38339f972
		summarizeBy: none
		sourceColumn: cost_change_event

		annotation SummarizationSetBy = Automatic

	column cost_change_event_fall
		dataType: string
		lineageTag: f159f4d0-706d-4941-a640-3a4eed31e36a
		summarizeBy: none
		sourceColumn: cost_change_event_fall

		annotation SummarizationSetBy = Automatic

	column cost_change_start
		dataType: string
		lineageTag: 6c4fdd75-0170-47ab-a9f5-521784f8a370
		summarizeBy: none
		sourceColumn: cost_change_start

		annotation SummarizationSetBy = Automatic

	column cost_change_start_fall
		dataType: string
		lineageTag: 5e6d357a-0ac6-41ca-899d-c15e81e44e3f
		summarizeBy: none
		sourceColumn: cost_change_start_fall

		annotation SummarizationSetBy = Automatic

	column dreamteam_count
		dataType: string
		lineageTag: 08240fcc-18d6-475e-9a55-f48fe29007aa
		summarizeBy: none
		sourceColumn: dreamteam_count

		annotation SummarizationSetBy = Automatic

	column 'Position ID'
		dataType: string
		lineageTag: ff744a23-f45c-451d-bda4-4e323eab48fb
		summarizeBy: none
		sourceColumn: Position ID

		annotation SummarizationSetBy = Automatic

	column ep_next
		dataType: double
		lineageTag: c64e2f0a-28c3-4273-b564-bc61ea764980
		summarizeBy: sum
		sourceColumn: ep_next

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ep_this
		dataType: double
		lineageTag: 60d6da5f-794d-4182-896b-97f2db49aff6
		summarizeBy: sum
		sourceColumn: ep_this

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column event_points
		dataType: string
		lineageTag: 3df50818-7f81-47cb-b8d4-e917ef46c886
		summarizeBy: none
		sourceColumn: event_points

		annotation SummarizationSetBy = Automatic

	column first_name
		dataType: string
		lineageTag: 39213876-326e-41a5-9617-c0c37360480a
		summarizeBy: none
		sourceColumn: first_name

		annotation SummarizationSetBy = Automatic

	column form
		dataType: string
		lineageTag: 54936bfd-3249-49c5-83e1-561156f3e63d
		summarizeBy: none
		sourceColumn: form

		annotation SummarizationSetBy = Automatic

	column id
		dataType: string
		lineageTag: e9346240-7be7-49b7-9c78-dbc9f45ec1ef
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column in_dreamteam
		dataType: string
		lineageTag: bf616a3c-d602-499d-b8a8-0bfcf5315cd5
		summarizeBy: none
		sourceColumn: in_dreamteam

		annotation SummarizationSetBy = Automatic

	column news
		dataType: string
		lineageTag: 42c55fd6-3e9a-4f05-a7c3-c96582f9ad13
		summarizeBy: none
		sourceColumn: news

		annotation SummarizationSetBy = Automatic

	column news_added
		dataType: string
		lineageTag: 2ddd8956-a8fd-4ebd-a00c-ce6888d6cef2
		summarizeBy: none
		sourceColumn: news_added

		annotation SummarizationSetBy = Automatic

	column now_cost
		dataType: string
		lineageTag: 2108e72c-3911-4b3a-9aa1-6cfd8e93a1dd
		summarizeBy: none
		sourceColumn: now_cost

		annotation SummarizationSetBy = Automatic

	column photo
		dataType: string
		lineageTag: 48d78f4b-8cdf-465f-af20-c6bfc250f9f6
		summarizeBy: none
		sourceColumn: photo

		annotation SummarizationSetBy = Automatic

	column points_per_game
		dataType: string
		lineageTag: 79487ea1-74ca-4355-992b-0f15001e66f6
		summarizeBy: none
		sourceColumn: points_per_game

		annotation SummarizationSetBy = Automatic

	column second_name
		dataType: string
		lineageTag: fc544c23-f356-4787-a528-ec62df5a17cd
		summarizeBy: none
		sourceColumn: second_name

		annotation SummarizationSetBy = Automatic

	column selected_by_percent
		dataType: string
		lineageTag: 62b18eab-8e8e-44a1-8f92-c5ff95574e2a
		summarizeBy: none
		sourceColumn: selected_by_percent

		annotation SummarizationSetBy = Automatic

	column special
		dataType: string
		lineageTag: 35435108-4d4b-47ea-87d4-ae05c975d557
		summarizeBy: none
		sourceColumn: special

		annotation SummarizationSetBy = Automatic

	column squad_number
		dataType: string
		lineageTag: 0b9976ad-ffb8-4e84-8a61-ca4f23e7a0b9
		summarizeBy: none
		sourceColumn: squad_number

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: c6f51c74-49d3-4eae-9a6a-30a90a807d20
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column team
		dataType: string
		lineageTag: 0191dd50-37ee-47ce-871c-f8ee09331c45
		summarizeBy: none
		sourceColumn: team

		annotation SummarizationSetBy = Automatic

	column team_code
		dataType: string
		lineageTag: 1580f867-8171-4ff7-a5a8-0aee3eefc98d
		summarizeBy: none
		sourceColumn: team_code

		annotation SummarizationSetBy = Automatic

	column total_points
		dataType: string
		lineageTag: 7b40704d-14ec-4c5c-8a7b-a4192f28e6c2
		summarizeBy: none
		sourceColumn: total_points

		annotation SummarizationSetBy = Automatic

	column transfers_in
		dataType: string
		lineageTag: 32dc24fe-a7e1-4705-9420-72ba100f51f1
		summarizeBy: none
		sourceColumn: transfers_in

		annotation SummarizationSetBy = Automatic

	column transfers_in_event
		dataType: string
		lineageTag: 04ced3e4-5a29-4ef5-a3a0-6d67f6c1bc7a
		summarizeBy: none
		sourceColumn: transfers_in_event

		annotation SummarizationSetBy = Automatic

	column transfers_out
		dataType: string
		lineageTag: 96ff3b86-b0f8-4543-8ba4-9ec9a24401ef
		summarizeBy: none
		sourceColumn: transfers_out

		annotation SummarizationSetBy = Automatic

	column transfers_out_event
		dataType: string
		lineageTag: abbf448d-68a4-4710-837b-953f971ecd99
		summarizeBy: none
		sourceColumn: transfers_out_event

		annotation SummarizationSetBy = Automatic

	column value_form
		dataType: string
		lineageTag: b017b241-3f29-4081-8cf3-b7bfd661148e
		summarizeBy: none
		sourceColumn: value_form

		annotation SummarizationSetBy = Automatic

	column value_season
		dataType: string
		lineageTag: 935ba17d-267c-4653-9095-c177f50ee6d2
		summarizeBy: none
		sourceColumn: value_season

		annotation SummarizationSetBy = Automatic

	column web_name
		dataType: string
		lineageTag: 715dada2-f7ec-4d1c-a24a-ec09a5d0f7f4
		summarizeBy: none
		sourceColumn: web_name

		annotation SummarizationSetBy = Automatic

	column minutes
		dataType: string
		lineageTag: b3c51667-3cbc-47e1-bed7-8dd330158d8b
		summarizeBy: none
		sourceColumn: minutes

		annotation SummarizationSetBy = Automatic

	column goals_scored
		dataType: string
		lineageTag: 7503f2a1-c941-44df-9f40-dc4bfcbb5f5a
		summarizeBy: none
		sourceColumn: goals_scored

		annotation SummarizationSetBy = Automatic

	column assists
		dataType: string
		lineageTag: ff1c2d95-b3f7-4917-86cc-c4701784319a
		summarizeBy: none
		sourceColumn: assists

		annotation SummarizationSetBy = Automatic

	column clean_sheets
		dataType: string
		lineageTag: c14bbde0-dd9d-41c3-b34f-7d92e0ce5227
		summarizeBy: none
		sourceColumn: clean_sheets

		annotation SummarizationSetBy = Automatic

	column goals_conceded
		dataType: string
		lineageTag: 7c8ddbad-392b-4df1-9f2c-61fba1689dc5
		summarizeBy: none
		sourceColumn: goals_conceded

		annotation SummarizationSetBy = Automatic

	column own_goals
		dataType: string
		lineageTag: f9b2778a-2fe6-4ce0-8e57-199ad4697927
		summarizeBy: none
		sourceColumn: own_goals

		annotation SummarizationSetBy = Automatic

	column penalties_saved
		dataType: string
		lineageTag: 4fb73dfe-a5ab-4480-8df1-3d22780625fc
		summarizeBy: none
		sourceColumn: penalties_saved

		annotation SummarizationSetBy = Automatic

	column penalties_missed
		dataType: string
		lineageTag: 323dca92-002c-48f7-a588-0f83b393a6e9
		summarizeBy: none
		sourceColumn: penalties_missed

		annotation SummarizationSetBy = Automatic

	column yellow_cards
		dataType: string
		lineageTag: 16bc3b54-a11b-445c-a90f-6bc5bdc900dc
		summarizeBy: none
		sourceColumn: yellow_cards

		annotation SummarizationSetBy = Automatic

	column red_cards
		dataType: string
		lineageTag: 4b4503f6-0cdf-4842-bb10-9e1f64f911cc
		summarizeBy: none
		sourceColumn: red_cards

		annotation SummarizationSetBy = Automatic

	column saves
		dataType: string
		lineageTag: 77242d75-b2fb-476b-ad21-413d24088dfa
		summarizeBy: none
		sourceColumn: saves

		annotation SummarizationSetBy = Automatic

	column bonus
		dataType: string
		lineageTag: 8038945e-bf91-4a47-a454-07277f4fd228
		summarizeBy: none
		sourceColumn: bonus

		annotation SummarizationSetBy = Automatic

	column bps
		dataType: string
		lineageTag: c4c8026d-ba26-4610-bdce-614ca7d29b0a
		summarizeBy: none
		sourceColumn: bps

		annotation SummarizationSetBy = Automatic

	column influence
		dataType: string
		lineageTag: 5b2085c3-201b-4f84-96bd-9a1da6467ffd
		summarizeBy: none
		sourceColumn: influence

		annotation SummarizationSetBy = Automatic

	column creativity
		dataType: string
		lineageTag: 13f95cc5-bb1d-4d61-b7d0-18ffddcbb46e
		summarizeBy: none
		sourceColumn: creativity

		annotation SummarizationSetBy = Automatic

	column threat
		dataType: string
		lineageTag: fad5d154-2e4f-4957-bbd8-70b46554d7e0
		summarizeBy: none
		sourceColumn: threat

		annotation SummarizationSetBy = Automatic

	column ict_index
		dataType: string
		lineageTag: c45acbe7-0e03-4b5e-8938-d57f34a63cd3
		summarizeBy: none
		sourceColumn: ict_index

		annotation SummarizationSetBy = Automatic

	column starts
		dataType: string
		lineageTag: 17ec4f9b-eaf8-4de7-b46e-91235aa0bb40
		summarizeBy: none
		sourceColumn: starts

		annotation SummarizationSetBy = Automatic

	column expected_goals
		dataType: string
		lineageTag: bbd35bf3-a1c9-4cb4-8da0-54178dfb320e
		summarizeBy: none
		sourceColumn: expected_goals

		annotation SummarizationSetBy = Automatic

	column expected_assists
		dataType: string
		lineageTag: 67c6bcf3-06a5-4eed-ad45-a33b90564fc6
		summarizeBy: none
		sourceColumn: expected_assists

		annotation SummarizationSetBy = Automatic

	column expected_goal_involvements
		dataType: string
		lineageTag: dd315fc6-1369-411e-9383-49af13edefc7
		summarizeBy: none
		sourceColumn: expected_goal_involvements

		annotation SummarizationSetBy = Automatic

	column expected_goals_conceded
		dataType: string
		lineageTag: 30d084b6-8ec1-44d1-811d-d010c480640f
		summarizeBy: none
		sourceColumn: expected_goals_conceded

		annotation SummarizationSetBy = Automatic

	column influence_rank
		dataType: string
		lineageTag: a76b1a1d-4d3f-4519-a15b-1d7001d0c08e
		summarizeBy: none
		sourceColumn: influence_rank

		annotation SummarizationSetBy = Automatic

	column influence_rank_type
		dataType: string
		lineageTag: 50e6c794-96d2-416f-847a-6314e136b1f6
		summarizeBy: none
		sourceColumn: influence_rank_type

		annotation SummarizationSetBy = Automatic

	column creativity_rank
		dataType: string
		lineageTag: cc857efb-d012-47cd-a56d-ea647ed0a485
		summarizeBy: none
		sourceColumn: creativity_rank

		annotation SummarizationSetBy = Automatic

	column creativity_rank_type
		dataType: string
		lineageTag: 8d423f65-74f7-4832-b9b2-b4a2f9b30c50
		summarizeBy: none
		sourceColumn: creativity_rank_type

		annotation SummarizationSetBy = Automatic

	column threat_rank
		dataType: string
		lineageTag: 5423a0d4-1e9e-4ec4-8539-4de2886740b7
		summarizeBy: none
		sourceColumn: threat_rank

		annotation SummarizationSetBy = Automatic

	column threat_rank_type
		dataType: string
		lineageTag: e75e62d4-da08-4060-95af-069c6f1ad986
		summarizeBy: none
		sourceColumn: threat_rank_type

		annotation SummarizationSetBy = Automatic

	column ict_index_rank
		dataType: string
		lineageTag: 0d5a7bbb-57ef-4389-b0cd-4b2a33cc2cdc
		summarizeBy: none
		sourceColumn: ict_index_rank

		annotation SummarizationSetBy = Automatic

	column ict_index_rank_type
		dataType: string
		lineageTag: 88085c47-c421-497f-91ea-5b6e5dd659ec
		summarizeBy: none
		sourceColumn: ict_index_rank_type

		annotation SummarizationSetBy = Automatic

	column corners_and_indirect_freekicks_order
		dataType: string
		lineageTag: 47ccab49-835f-462b-88b9-bbbe7f83e1e1
		summarizeBy: none
		sourceColumn: corners_and_indirect_freekicks_order

		annotation SummarizationSetBy = Automatic

	column corners_and_indirect_freekicks_text
		dataType: string
		lineageTag: e226ab11-6385-46db-b766-415828d1602e
		summarizeBy: none
		sourceColumn: corners_and_indirect_freekicks_text

		annotation SummarizationSetBy = Automatic

	column direct_freekicks_order
		dataType: string
		lineageTag: 6278517f-c1bc-4ed2-8a70-c30bfdcc04f8
		summarizeBy: none
		sourceColumn: direct_freekicks_order

		annotation SummarizationSetBy = Automatic

	column direct_freekicks_text
		dataType: string
		lineageTag: c22507d7-e511-4e4e-ab6a-19a0490b5807
		summarizeBy: none
		sourceColumn: direct_freekicks_text

		annotation SummarizationSetBy = Automatic

	column penalties_order
		dataType: string
		lineageTag: a2403f0a-74cd-48e6-aecc-d14a124bc6d2
		summarizeBy: none
		sourceColumn: penalties_order

		annotation SummarizationSetBy = Automatic

	column penalties_text
		dataType: string
		lineageTag: 7b0f1e27-9ba5-496b-9984-8339a9fd8685
		summarizeBy: none
		sourceColumn: penalties_text

		annotation SummarizationSetBy = Automatic

	column expected_goals_per_90
		dataType: string
		lineageTag: 497c24dc-0f53-4656-8de9-661a3935f604
		summarizeBy: none
		sourceColumn: expected_goals_per_90

		annotation SummarizationSetBy = Automatic

	column saves_per_90
		dataType: string
		lineageTag: dea73c4d-3b4e-48bb-aadb-baaf18360ea6
		summarizeBy: none
		sourceColumn: saves_per_90

		annotation SummarizationSetBy = Automatic

	column expected_assists_per_90
		dataType: string
		lineageTag: b9a745f4-b2cf-4fe2-9d45-6684f280c687
		summarizeBy: none
		sourceColumn: expected_assists_per_90

		annotation SummarizationSetBy = Automatic

	column expected_goal_involvements_per_90
		dataType: string
		lineageTag: 8b830885-e007-4c47-b3c7-59dbc53b2039
		summarizeBy: none
		sourceColumn: expected_goal_involvements_per_90

		annotation SummarizationSetBy = Automatic

	column expected_goals_conceded_per_90
		dataType: string
		lineageTag: b20c6ddd-44e4-4a8c-b874-1bcd734ae0d6
		summarizeBy: none
		sourceColumn: expected_goals_conceded_per_90

		annotation SummarizationSetBy = Automatic

	column goals_conceded_per_90
		dataType: string
		lineageTag: 16631099-5264-4968-a214-ce1579c7b5b7
		summarizeBy: none
		sourceColumn: goals_conceded_per_90

		annotation SummarizationSetBy = Automatic

	column now_cost_rank
		dataType: string
		lineageTag: 56e33263-e7da-4c40-81ec-d9f76407941c
		summarizeBy: none
		sourceColumn: now_cost_rank

		annotation SummarizationSetBy = Automatic

	column now_cost_rank_type
		dataType: string
		lineageTag: 367f0a26-883c-4c91-bdc2-d5171ad85ecf
		summarizeBy: none
		sourceColumn: now_cost_rank_type

		annotation SummarizationSetBy = Automatic

	column form_rank
		dataType: string
		lineageTag: fa1ab877-7f72-4b6c-b64f-f9f55570b14b
		summarizeBy: none
		sourceColumn: form_rank

		annotation SummarizationSetBy = Automatic

	column form_rank_type
		dataType: string
		lineageTag: 09abed9f-384a-4525-98f9-fe4cd585a649
		summarizeBy: none
		sourceColumn: form_rank_type

		annotation SummarizationSetBy = Automatic

	column points_per_game_rank
		dataType: string
		lineageTag: 023b9f75-87a0-403b-98e8-0986ad57790c
		summarizeBy: none
		sourceColumn: points_per_game_rank

		annotation SummarizationSetBy = Automatic

	column points_per_game_rank_type
		dataType: string
		lineageTag: 2d5b809c-69a5-4622-86af-2078b3a85c56
		summarizeBy: none
		sourceColumn: points_per_game_rank_type

		annotation SummarizationSetBy = Automatic

	column selected_rank
		dataType: string
		lineageTag: dd665fcf-d943-4f72-8928-070f75974c12
		summarizeBy: none
		sourceColumn: selected_rank

		annotation SummarizationSetBy = Automatic

	column selected_rank_type
		dataType: string
		lineageTag: 2184b960-2cb2-4c8d-828e-2a78c55d0636
		summarizeBy: none
		sourceColumn: selected_rank_type

		annotation SummarizationSetBy = Automatic

	column starts_per_90
		dataType: string
		lineageTag: 27057904-12f8-4300-96d2-6c717785eca5
		summarizeBy: none
		sourceColumn: starts_per_90

		annotation SummarizationSetBy = Automatic

	column clean_sheets_per_90
		dataType: string
		lineageTag: 571c6048-bbc7-4d9b-bfcf-88d8c399c01c
		summarizeBy: none
		sourceColumn: clean_sheets_per_90

		annotation SummarizationSetBy = Automatic

	partition ClubAnalysis = m
		mode: import
		source =
				let
				    Source = Json.Document(Web.Contents("https://fantasy.premierleague.com/api/bootstrap-static/")),
				    elements = Source[elements],
				    #"Converted to Table" = Table.FromList(elements, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"chance_of_playing_next_round", "chance_of_playing_this_round", "code", "cost_change_event", "cost_change_event_fall", "cost_change_start", "cost_change_start_fall", "dreamteam_count", "element_type", "ep_next", "ep_this", "event_points", "first_name", "form", "id", "in_dreamteam", "news", "news_added", "now_cost", "photo", "points_per_game", "second_name", "selected_by_percent", "special", "squad_number", "status", "team", "team_code", "total_points", "transfers_in", "transfers_in_event", "transfers_out", "transfers_out_event", "value_form", "value_season", "web_name", "minutes", "goals_scored", "assists", "clean_sheets", "goals_conceded", "own_goals", "penalties_saved", "penalties_missed", "yellow_cards", "red_cards", "saves", "bonus", "bps", "influence", "creativity", "threat", "ict_index", "starts", "expected_goals", "expected_assists", "expected_goal_involvements", "expected_goals_conceded", "influence_rank", "influence_rank_type", "creativity_rank", "creativity_rank_type", "threat_rank", "threat_rank_type", "ict_index_rank", "ict_index_rank_type", "corners_and_indirect_freekicks_order", "corners_and_indirect_freekicks_text", "direct_freekicks_order", "direct_freekicks_text", "penalties_order", "penalties_text", "expected_goals_per_90", "saves_per_90", "expected_assists_per_90", "expected_goal_involvements_per_90", "expected_goals_conceded_per_90", "goals_conceded_per_90", "now_cost_rank", "now_cost_rank_type", "form_rank", "form_rank_type", "points_per_game_rank", "points_per_game_rank_type", "selected_rank", "selected_rank_type", "starts_per_90", "clean_sheets_per_90"}, {"chance_of_playing_next_round", "chance_of_playing_this_round", "code", "cost_change_event", "cost_change_event_fall", "cost_change_start", "cost_change_start_fall", "dreamteam_count", "element_type", "ep_next", "ep_this", "event_points", "first_name", "form", "id", "in_dreamteam", "news", "news_added", "now_cost", "photo", "points_per_game", "second_name", "selected_by_percent", "special", "squad_number", "status", "team", "team_code", "total_points", "transfers_in", "transfers_in_event", "transfers_out", "transfers_out_event", "value_form", "value_season", "web_name", "minutes", "goals_scored", "assists", "clean_sheets", "goals_conceded", "own_goals", "penalties_saved", "penalties_missed", "yellow_cards", "red_cards", "saves", "bonus", "bps", "influence", "creativity", "threat", "ict_index", "starts", "expected_goals", "expected_assists", "expected_goal_involvements", "expected_goals_conceded", "influence_rank", "influence_rank_type", "creativity_rank", "creativity_rank_type", "threat_rank", "threat_rank_type", "ict_index_rank", "ict_index_rank_type", "corners_and_indirect_freekicks_order", "corners_and_indirect_freekicks_text", "direct_freekicks_order", "direct_freekicks_text", "penalties_order", "penalties_text", "expected_goals_per_90", "saves_per_90", "expected_assists_per_90", "expected_goal_involvements_per_90", "expected_goals_conceded_per_90", "goals_conceded_per_90", "now_cost_rank", "now_cost_rank_type", "form_rank", "form_rank_type", "points_per_game_rank", "points_per_game_rank_type", "selected_rank", "selected_rank_type", "starts_per_90", "clean_sheets_per_90"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded Column1",{{"element_type", "Position ID"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Position ID", type text}}),
				    #"Sorted Rows" = Table.Sort(#"Changed Type",{{"expected_goals", Order.Descending}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Sorted Rows",{{"ep_this", type number}, {"ep_next", type number}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

